main_proj/blog_app/urls.py
from django.urls import path
from blog_app import views

app_name = 'blog_app'

urlpatterns = [
    path('', views.PostListView.as_view(), name='post_list'),
    path('post/<int:pk>/', views.PostDetailView.as_view(), name='post_detail'),
    path('about/', views.AboutView.as_view(), name='about'),
    path('post/new/', views.CreatePostView.as_view(), name='post_new'),
    path('post/<int:pk>/edit/',views.PostUpdateView.as_view(), name='post_edit'),
    path('post/<int:pk>/remove/', views.PostDeleteView.as_view(), name='post_remove'),
    path('drafts/', views.DraftListView.as_view(), name='post_draft_list'),
    path('post/<int:pk>/comment/', views.add_comment_to_post, name='add_comment_to_post'),
    path('comment/<int:pk>/approve/', views.comment_approved, name='comment_approve'),
    path('comment/<int:pk>/remove/', views.comment_remove, name='comment_remove'),
    path('post/<int:pk>/publish/', views.post_publish, name='post_publish'),
]

main_proj/blog_project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth import views as auth_views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('blog_app.urls')),
    path('accounts/login/', auth_views.LoginView.as_view(), name='login'),
    path('accounts/logout/', auth_views.LogoutView.as_view(), name='logout', kwargs={'next_page':'/'})
    
]
 

main_proj/blog_app/models.py
from django.db import models
from django.contrib.auth.models import User
from django.utils import timezone
from django.urls import reverse
# Create your models here.

class Post(models.Model):
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    title = models.CharField(max_length=54)
    text =  models.TextField()
    created_date = models.DateTimeField(default=timezone.now())
    published_date = models.DateTimeField(blank=True, null=True)
 
    def publish(self):
        self.published_date = timezone.now()
        self.save()
    
    def approve_comments(self):
        return self.comments.filter(approved_comment=True)
    
    def get_absolute_url(self):
        return reverse("blog_app:post_detail", kwargs={"pk": self.pk})
    
    
    def __str__(self):
        return self.title 
    


class Comment(models.Model):
    post = models.ForeignKey(Post, related_name='comments', on_delete=models.CASCADE)
    author = models.CharField(max_length=52)
    text = models.TextField()
    created_date = models.DateTimeField(default=timezone.now())
    approved_comment = models.BooleanField(default=False)

    def approve(self):
        self.approved_comment = True
        self.save()
    
    def get_absolute_url(self):
        return reverse('blog_app:post_list')

    def __str__(self):
        return self.text

main_proj/blog_app/forms.py
from django import forms
from blog_app.models import Post, Comment

class PostForm(forms.ModelForm):
    
    class Meta():
        model = Post
        fields = ('author','title', 'text')

        widgets = {
            'title':forms.TextInput(attrs={
                'class':'textinputclass'
            }),

            'text':forms.Textarea(attrs={
                'class':'editable medium-editor-textarea'
            })
        } 
    

class CommentForm(forms.ModelForm):

    class Meta():
        model = Comment
        fields = ('author', 'text')

        widgets = {
            'author':forms.TextInput(attrs={
                'class':'textinputclass'
            }),
            
            'text':forms.Textarea(attrs={
                'class':'editable medium-editor-textarea'
            })
        }

main_proj/blog_app/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.utils import timezone 
from django.urls import reverse_lazy
from blog_app.models import Post, Comment
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.generic import (TemplateView, ListView,
                                  DetailView, CreateView,
                                  UpdateView, DeleteView)
from blog_app.forms import PostForm, CommentForm

# Create your views here. 

class AboutView(TemplateView):
    template_name = 'about.html'

class PostListView(ListView):
    model = Post

    def get_queryset(self):
        return Post.objects.filter(published_date__lte=timezone.now()).order_by('-published_date')
    

class PostDetailView(DetailView):
    model = Post 


class CreatePostView(LoginRequiredMixin, CreateView):
    login_url = '/login/' # before login
    redirect_field_name = 'blog_app/post_detail.html' #after login
    form_class = PostForm
    model = Post


class PostUpdateView(LoginRequiredMixin,UpdateView):
    login_url = '/login/' # before login
    redirect_field_name = 'blog_app/post_detail.html' #after login
    form_class = PostForm
    model = Post


class PostDeleteView(LoginRequiredMixin,DeleteView):
    model = Post
    success_url = reverse_lazy('blog_app:post_list')


class DraftListView(LoginRequiredMixin,ListView):
    login_url = '/login/'
    redirect_field_name = 'blog_app/post_list.html'
    model = Post

    def get_queryset(self):
        return Post.objects.filter(published_date__isnull=True).order_by('created_date')


#####################################################################################
#####################################################################################

@login_required
def post_publish(request, pk):
    post = get_object_or_404(Post, pk=pk)
    post.publish()
    return redirect('blog_app:post_detail', pk=pk)



@login_required
def add_comment_to_post(request, pk):
    post = get_object_or_404(Post, pk=pk)
    if request.method == 'POST':
        form = CommentForm(request.POST)
        if form.is_valid():
            comment = form.save(commit=False)
            comment.post = post
            comment.save()
            return redirect('blog_app:post_detail', pk=post.pk)
        
    else:
        form = CommentForm()
    
    return render(request, 'blog_app/comment_form.html', {'form':form})

@login_required
def comment_approved(request, pk):
    comment = get_object_or_404(Comment, pk=pk)
    comment.approve()
    return redirect('blog_app:post_detail', pk=comment.post.pk)


@login_required
def comment_remove(request, pk):
    comment = get_object_or_404(Comment, pk=pk)
    post_pk = comment.post.pk
    comment.delete()
    return redirect('blog_app:post_detail', pk=post_pk)

main_proj/blog_app/templates/blog_app/about.html
{% extends "blog_app/base.html" %}

{% block content %}
<h1>This Is The Corporated Blog</h1>
<p>Thanks For Visiting.</p>
{% endblock %}

main_proj/blog_app/templates/blog_app/base.html
<!DOCTYPE html>
{% load static %}
<html> 
    <head>
        <title>Blog App</title>
        <!-- bootstrap -->
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-eOJMYsd53ii+scO/bJGFsiCZc+5NDVN2yr8+0RDqr0Ql0h+rP48ckxlpbzKgwra6" crossorigin="anonymous">
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css" integrity="sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp" crossorigin="anonymous">
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">

        <!-- medium style editor -->
        <script src="//cdn.jsdelivr.net/npm/medium-editor@latest/dist/js/medium-editor.min.js"></script>
        <link rel="stylesheet" href="//cdn.jsdelivr.net/npm/medium-editor@latest/dist/css/medium-editor.min.css" type="text/css" media="screen" charset="utf-8">

        <!-- custom css -->
        <link rel="stylesheet" href="{% static 'css/blog.css' %}">

        <!-- google fonts  -->
        <link href="https://fonts.googleapis.com/css2?family=Montserrat:wght@100&family=Russo+One&display=swap" rel="stylesheet">

    </head>
    <body class="loader">
        
        <!-- NAVBAR -->

        <nav class="navbar navbar-expand-lg navbar-dark bg-dark techfont">

            <a class="navbar-brand bigbrand" href="{% url 'blog_app:post_list' %}">Blog App</a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
              <span class="navbar-toggler-icon"></span>
            </button>

            <div class="collapse navbar-collapse" id="navbarNav">
              <ul class="navbar-nav">

                <li class="nav-item">
                  <a class="nav-link" href="{% url 'blog_app:about' %}">About</a>
                </li>

                <li class="nav-item">
                  <a class="nav-link" href="https://github.com">Github</a>
                </li>
                
                <li class="nav-item">
                  <a class="nav-link" href="https://linkedin.com">LinkedIn</a>
                </li>
              </ul>

              <ul class="nav navbar-nav navbar-right">
                {% if user.is_authenticated %}
                <li>
                  <a href="{% url 'blog_app:post_new' %}">New Post</a>
                </li>

                <li>
                  <a href="{% url 'blog_app:post_draft_list' %}">Drafts</a>
                </li>

                <li>
                  <a href="{% url 'logout' %}">Log Out</a>
                </li>

                <li>
                  <a>Welcome: {{user.username}}</a>
                </li>

                {% else %}
                <li><a class='nav navbar-right' href="{% url 'login' %}"><span class='glyphicon glyphicon-user'></span></a></li>

                {% endif %}
              </ul>

            </div>
          </nav>

          <!-- CONTENT BLOCK -->
          <div class="content container">
            <div class="row">
              <div class="col-md-8">
                <div class="blog_posts">
                  {% block content %}
                  
                  
                  {% endblock %}
                </div>
              </div>
          </div>

    </body>
</html>

main_proj/blog_app/templates/blog_app/comment_form.html
{% extends "blog_app/base.html" %}

{% block content %}
<h1>New Comment</h1>
<form class="post-form" method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit" class="btn btn-default">Post Comment</button>
</form>

<script>
    var editor = new MediumEditor('.editable');
</script>
{% endblock %} 

main_proj/blog_app/templates/blog_app/post_confirm_delete.html
{% extends "blog_app/base.html" %}

{% block content %}
   <form method="POST">
       {% csrf_token %}
       <p>Are you sure you want to delete this {{context}}?</p>
       <input type="submit" class="btn btn-danger" value="Confirm Delete">
   </form>
{% endblock %}

main_proj/blog_app/templates/blog_app/post_detail.html
{% extends "blog_app/base.html" %}

{% block content %}

<h1 class="posttitle loader">{{post.title}}</h1>
{% if post.published_date %}
<div class="date postdate">
    {{post.published_date}}
</div>
{% else %} 
<a class="btn btn-default" href="{% url 'blog_app:post_publish' pk=post.pk %}">Publish</a>
{% endif %}

<p class="postcontent">{{post.text|safe|linebreaksbr}}</p>


{% if user.is_authenticated %}
    <a class="btn btn-primary" href="{% url 'blog_app:post_edit' pk=post.pk %}">
    <span class="glyphicon glyphicon-pencil"></span>
    </a>

    <a class="btn btn-primary" href="{% url 'blog_app:post_remove' pk=post.pk %}">
        <span class="glyphicon glyphicon-remove"></span>
    </a>
    
{% endif %}

<hr>
<a class="btn btn-primary btn-comment" href="{% url 'blog_app:add_comment_to_post' pk=post.pk %}">Add Comment</a>

<div class="container">
    {% for comment in post.comments.all %}
    <br>
    {% if user.is_authenticated or comment.approved_comment %}
    {{comment.created_date}}
        {% if not comment.approved_comment %}
        <a class="btn btn-primary" href="{% url 'blog_app:comment_remove' pk=comment.pk %}">
            <span class="glyphicon glyphicon-remove"></span>
            </a>
        
            <a class="btn btn-primary" href="{% url 'blog_app:comment_approve' pk=comment.pk %}">
                <span class="glyphicon glyphicon-ok"></span>
            </a>
            
        {% endif %}

        <p>{{comment.text|safe|linebreaks}}</p>
        <p>{{comment.author}}</p>
    {% endif %}
    {% empty %}
    <P>No Comments!</P>
    {% endfor %}

{% endblock %}

main_proj/blog_app/templates/blog_app/post_draft_list.html
{% extends "blog_app/base.html" %}

{% block content %}
    {% for post in posts %}
    <div class="post">
        <p class="date">Created: {{post.created_date|date:'d-m-Y'}}</p>
        <h1><a href="{% url 'blog_app:post_detail' pk=post.pk %}">{{post.title}}</a></h1>
        <p>{{post.text|truncatechars:200}}</p>
    </div>
    {% endfor %}
{% endblock %}

main_proj/blog_app/templates/blog_app/post_form.html
{% extends "blog_app/base.html" %}

{% block content %}
<h1>New Post</h1>
<form class="post-form" method="post" >
    {% csrf_token %}
    {{form.as_p}}
    <button type="submit" class="save btn btn-default">Save</button>
</form>

<script>
    var editor = new MediumEditor('.editable');
</script>

{% endblock %}

main_proj/blog_app/templates/blog_app/post_list.html
{% extends "blog_app/base.html" %}

{% block content %}
<div class="centerstage">
    {% for post in post_list %}
    <div class="post">
        <h1><a href="{% url 'blog_app:post_detail' pk=post.pk %}">{{post.title}}</a></h1>
        <div class="date">
            <p>Published on: {{post.published_date|date:"D M Y"}}</p>
        </div>

        <div>
        <a href="{% url 'blog_app:post_detail' pk=post.pk %}">Comments: {{post.approve_comments.count}}</a>
        </div>
    </div>
    {% endfor %}
</div>
{% endblock %}